### ISSUE TITLE
bug when checking previously computed outputs

### ISSUE THREAD

**Issue by sforazz** [monashbiomedicalimaging/arcana#23] opened 2018-05-15 05:59 UTC
It seems there is a bug when trying to restart a crashed workflow using the local archive (I haven't tested with xnat). When checking the precomputed outputs it always return that there is nothing to do even if the final output has not been already produced. In order to make the pipeline work you need to delete the cache dir and all the previously produced outputs.

**Comment by tclose** [comment] 2018-05-25 04:04
Duplicate of #40, has been resolved

**Closed by tclose** 2018-05-25 04:04 UTC
Labels: bug, duplicate
